---
blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/demaconsulting/VersionMark
    about: Read the documentation for VersionMark
  - name: ðŸ’¬ Discussions
    url: https://github.com/demaconsulting/VersionMark/discussions
    about: Ask questions and discuss with the community
