---
blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/demaconsulting/TemplateDotNetTool
    about: Read the documentation for TemplateDotNetTool
  - name: ðŸ’¬ Discussions
    url: https://github.com/demaconsulting/TemplateDotNetTool/discussions
    about: Ask questions and discuss with the community
